### ISSUE TITLE
适应多个数据源的 Spring Boot Auto Configuration

### ISSUE THREAD

**Issue by yiding-he** [yiding-he/hydrogen-dao#1]

**Comment by yiding-he** [comment]
使用多数据源的配置示例：

```
hydrogen-dao:
  data-sources:
    default:
      url: jdbc:mysql://localhost/demo?useSSL=false
      username: root
      password: root123
    datasource2:
      url: jdbc:mysql://localhost/demo?useSSL=false
      username: root
      password: root123
    datasource3:
      url: jdbc:mysql://localhost/demo?useSSL=false
      username: root
      password: root123
```
